<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/25 12:01:47

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=systemclient',
  'username' => 'root',
  'password' => 'aman12pl',
  'name' => 'doctrine',
)),);
