# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        System Mailingowy
    description:  System Mailingowy
    keywords:     System Mailingowy
    language:     System Mailingowy
    robots:       index, follow

  stylesheets:    
    - bootstrap/bootstrap.min.css
    - main.css

  javascripts:    
    - jQuery.js
    - bootstrap/bootstrap.min.js
    - bootstrap/bootstrap-dropdown.js
    - main.js
    - tiny_mce/tiny_mce.js

  has_layout:     true
  layout:         layout
