<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/15 18:48:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=SystemCore',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
